---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: rancher-web
  name: rancher-web-deployment
  labels:
    app: rancher-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rancher-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rancher-web
    spec:
      affinity:
        podAffinity: {}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector: {}
              topologyKey: kubernetes.io/hostname
            weight: 1
      containers:
      - image: registry.containers.rmntest.com/public/httpd:latest
        imagePullPolicy: Always
        name: rancher-web
        ports:
        - containerPort: 80
      tolerations:
      - key: cattle.io/os
        operator: "Equal"
        value: "linux"
        effect: NoSchedule
      nodeSelector:
        kubernetes.io/os: linux
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: windows-core-test
  name: windows-core-iis-deployment
  labels:
    app: windows-core-iis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: windows-core-iis
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: windows-core-iis
    spec:
      affinity:
        podAffinity: {}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector: {}
              topologyKey: kubernetes.io/hostname
            weight: 1
      containers:
      - image: registry.containers.rmntest.com/public/windows-core-iis:latest
        imagePullPolicy: Always
        name: windows-core-iis
        env:
        - name: PATH_BASE
          value: /iis
      nodeSelector:
        kubernetes.io/os: windows
