---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: rancher-web-ingress
  namespace: rancher-web
spec:
  rules:
  - host: rancherweb.containers.rmntest.com
    http:
      paths:
      - backend:
          service:
            name: rancher-web-service
            port:
              number: 80
        path: /
	path: /test(/|$)(.*)
        pathType: Prefix
  tls:
  - hosts:
    - '*.containers.rmntest.com'
    secretName: container-rmntest-cert
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: windows-core-iis-ingress
  namespace: windows-core-test
spec:
  rules:
  - host: rancher.containers.rmntest.com
    http:
      paths:
      - backend:
          service:
            name: windows-core-iis-service
            port:
              number: 80
        path: /iis
        path: /test(/|$)(.*)
        pathType: Prefix
  tls:
  - hosts:
    - '*.containers.rmntest.com'
    secretName: container-rmntest-cert
