---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: rancher-web-ingress
  namespace: rancher-web
spec:
  rules:
  - host: rancherweb.containers.rmntest.com
    http:
      paths:
      - backend:
          service:
            name: rancher-web-service
            port:
              number: 80
        path: /
        pathType: Prefix
